version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint --disable=E0611,E0401,E1101,W0621,C0103,C0411,C0303,W0622,C0114,W0613,W0702,W0612,C0326,C0303,C0115,C0304,C0114,C0301,C0410,W0611 *.py **/*.py || true
  build:
    commands:
      - echo "Build phase"
      # Add build commands here
  post_build:
    commands:
      - echo "Post-build phase"
      # Add post-build commands here
artifacts:
  files:
    - '**/*'
