# Generated by Django 4.2 on 2023-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=25, null=True)),
                ('contact', models.IntegerField()),
                ('parkingslot', models.IntegerField()),
                ('entrydatetime', models.DateTimeField()),
                ('vehicle', models.CharField(max_length=25)),
            ],
        ),
    ]
